version: '3.9'

services:
#  db:
#    container_name:  h2-jaiminho
#    image: boaglio/h2:latest
#    network_mode: host
#    ulimits:
#      nofile:
#        soft: 65536
#        hard: 65536
#    environment:
#      - H2_OPTIONS=-ifNotExists
#    volumes:
#     - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
#    deploy:
#      resources:
#        limits:
#          cpus: '0.65'
#          memory: '300MB'

  db:
    image: postgres:latest
    hostname: db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=rinha
      - POSTGRES_DB=rinhadepostgres
    network_mode: host
    volumes:
      - ./docker-entrypoint-initdb.d/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    command: postgres -c checkpoint_timeout=600 -c max_wal_size=2096 -c synchronous_commit=0 -c full_page_writes=0 -c fsync=off -c check_function_bodies=false
    deploy:
      resources:
        limits:
          cpus: '0.56'
          memory: '400MB'
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U admin -d rinhadepostgres'"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s

