version: '3.9'

services:
  db:
    container_name:  h2-jaiminho
    image: boaglio/h2:latest
    network_mode: host
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    environment:
      - H2_OPTIONS=-ifNotExists
    volumes:
     - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    deploy:
      resources:
        limits:
          cpus: '0.65'
          memory: '300MB'
